# Generated by Django 2.2 on 2019-04-21 11:41

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[(catalog.models.StatusChoice('active'), 'active'), (catalog.models.StatusChoice('inactive'), 'inactive')], max_length=20)),
                ('url_key', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('price_type', models.CharField(choices=[(catalog.models.PriceType('regular'), 'regular'), (catalog.models.PriceType('special'), 'special'), (catalog.models.PriceType('group'), 'group')], max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[(catalog.models.StatusChoice('active'), 'active'), (catalog.models.StatusChoice('inactive'), 'inactive')], max_length=20)),
                ('url_key', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('products', models.ManyToManyField(to='catalog.Product')),
            ],
        ),
    ]
